export const LOAD_COUNTS = 'app/Home/LOAD_COUNTS';
export const COUNTS_LOADING_SUCCESS = 'app/Home/COUNTS_LOADING_SUCCESS';
export const COUNTS_LOADING_ERROR = 'app/Home/COUNTS_LOADING_ERROR';
export const STATISTIC_SUCCESSFULLY_LOADED = 'app/Statistic/STATISTIC_SUCCESSFULLY_LOADED';
